spring.application.name=module5
spring.datasource.url=jdbc:mysql://localhost:3306/prod-ready-features?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=10Vivek12#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#spring.jpa.open-in-view=false


#security configs
#spring.security.user.name=vivek
#spring.security.user.password=pass

jwt.secretKey = bd8ob3827bd846843b4739bd98983hiijewkfbejbfjbjfbjwfbbkjbciuew837erb9ubfubfbffb784bfybkabkyyfb874